version: '3'
services:
  python3:
    restart: always
    build: .
    image: python:3.7
    container_name: 'mg-python'
    working_dir: '/opt/app/'
    tty: true
    volumes:
      - ./tmp:/opt/app/tmp